<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504234822 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE action_logs (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, user_id INT DEFAULT NULL, INDEX IDX_866E7D52A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE approval_history (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(20) NOT NULL, comment LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, conge_id INT DEFAULT NULL, absence_id INT DEFAULT NULL, approver_id INT NOT NULL, INDEX IDX_B3FACF0DCAAC9A59 (conge_id), INDEX IDX_B3FACF0D2DFF238F (absence_id), INDEX IDX_B3FACF0DBB23766C (approver_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE jours_feries (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, date DATE NOT NULL, pays VARCHAR(10) NOT NULL, type VARCHAR(50) NOT NULL, annee INT NOT NULL, date_creation DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, reference_link VARCHAR(255) DEFAULT NULL, is_read TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, user_id INT NOT NULL, INDEX IDX_BF5476CAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE planning_rules (id INT AUTO_INCREMENT NOT NULL, max_simultaneous_absences INT NOT NULL, max_absence_percentage NUMERIC(5, 2) NOT NULL, require_minimum_coverage TINYINT(1) NOT NULL, blocked_dates JSON DEFAULT NULL, created_at DATETIME NOT NULL, manager_id INT DEFAULT NULL, INDEX IDX_183623A3783E3463 (manager_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL, available_at DATETIME NOT NULL, delivered_at DATETIME DEFAULT NULL, INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 (queue_name, available_at, delivered_at, id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE action_logs ADD CONSTRAINT FK_866E7D52A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE approval_history ADD CONSTRAINT FK_B3FACF0DCAAC9A59 FOREIGN KEY (conge_id) REFERENCES conge (id)');
        $this->addSql('ALTER TABLE approval_history ADD CONSTRAINT FK_B3FACF0D2DFF238F FOREIGN KEY (absence_id) REFERENCES absence (id)');
        $this->addSql('ALTER TABLE approval_history ADD CONSTRAINT FK_B3FACF0DBB23766C FOREIGN KEY (approver_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE planning_rules ADD CONSTRAINT FK_183623A3783E3463 FOREIGN KEY (manager_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY absence_ibfk_1');
        $this->addSql('ALTER TABLE absence CHANGE employe_id employe_id INT DEFAULT NULL, CHANGE type_absence type_absence VARCHAR(255) NOT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX employe_id ON absence');
        $this->addSql('CREATE INDEX IDX_765AE0C91B65292 ON absence (employe_id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT absence_ibfk_1 FOREIGN KEY (employe_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY candidature_ibfk_2');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY candidature_ibfk_3');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY candidature_ibfk_2');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY candidature_ibfk_3');
        $this->addSql('ALTER TABLE candidature CHANGE statut statut VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT FK_E33BD3B88D0EB82 FOREIGN KEY (candidat_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT FK_E33BD3B84CC8505A FOREIGN KEY (offre_id) REFERENCES offre_emploi (id)');
        $this->addSql('DROP INDEX candidat_id ON candidature');
        $this->addSql('CREATE INDEX IDX_E33BD3B88D0EB82 ON candidature (candidat_id)');
        $this->addSql('DROP INDEX offre_id ON candidature');
        $this->addSql('CREATE INDEX IDX_E33BD3B84CC8505A ON candidature (offre_id)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT candidature_ibfk_2 FOREIGN KEY (offre_id) REFERENCES offre_emploi (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT candidature_ibfk_3 FOREIGN KEY (candidat_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY commentaire_ibfk_1');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY commentaire_ibfk_2');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY commentaire_ibfk_1');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY commentaire_ibfk_2');
        $this->addSql('ALTER TABLE commentaire CHANGE contenu contenu LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC38B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('DROP INDEX publication_id ON commentaire');
        $this->addSql('CREATE INDEX IDX_67F068BC38B217A7 ON commentaire (publication_id)');
        $this->addSql('DROP INDEX user_id ON commentaire');
        $this->addSql('CREATE INDEX IDX_67F068BCA76ED395 ON commentaire (user_id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT commentaire_ibfk_1 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT commentaire_ibfk_2 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY conge_ibfk_1');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY conge_ibfk_2');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY conge_ibfk_1');
        $this->addSql('ALTER TABLE conge CHANGE absence_id absence_id INT DEFAULT NULL, CHANGE commentaire_validation commentaire_validation LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT FK_2ED893482DFF238F FOREIGN KEY (absence_id) REFERENCES absence (id)');
        $this->addSql('DROP INDEX absence_id ON conge');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2ED893482DFF238F ON conge (absence_id)');
        $this->addSql('DROP INDEX manager_id ON conge');
        $this->addSql('CREATE INDEX IDX_2ED89348783E3463 ON conge (manager_id)');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT conge_ibfk_2 FOREIGN KEY (manager_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT conge_ibfk_1 FOREIGN KEY (absence_id) REFERENCES absence (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE entretien DROP FOREIGN KEY entretien_ibfk_3');
        $this->addSql('ALTER TABLE entretien DROP FOREIGN KEY entretien_ibfk_1');
        $this->addSql('ALTER TABLE entretien DROP FOREIGN KEY entretien_ibfk_2');
        $this->addSql('ALTER TABLE entretien CHANGE candidature_id candidature_id INT DEFAULT NULL, CHANGE admin_id admin_id INT DEFAULT NULL, CHANGE manager_id manager_id INT DEFAULT NULL, CHANGE duree_minutes duree_minutes INT DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL, CHANGE commentaire commentaire LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('DROP INDEX candidature_id ON entretien');
        $this->addSql('CREATE INDEX IDX_2B58D6DAB6121583 ON entretien (candidature_id)');
        $this->addSql('DROP INDEX admin_id ON entretien');
        $this->addSql('CREATE INDEX IDX_2B58D6DA642B8210 ON entretien (admin_id)');
        $this->addSql('DROP INDEX manager_id ON entretien');
        $this->addSql('CREATE INDEX IDX_2B58D6DA783E3463 ON entretien (manager_id)');
        $this->addSql('ALTER TABLE entretien ADD CONSTRAINT entretien_ibfk_3 FOREIGN KEY (manager_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE entretien ADD CONSTRAINT entretien_ibfk_1 FOREIGN KEY (candidature_id) REFERENCES candidature (id)');
        $this->addSql('ALTER TABLE entretien ADD CONSTRAINT entretien_ibfk_2 FOREIGN KEY (admin_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE feedback DROP FOREIGN KEY feedback_ibfk_2');
        $this->addSql('DROP INDEX employe_id ON feedback');
        $this->addSql('ALTER TABLE feedback DROP FOREIGN KEY feedback_ibfk_2');
        $this->addSql('ALTER TABLE feedback ADD priority VARCHAR(20) DEFAULT \'normal\' NOT NULL, ADD auto_response LONGTEXT DEFAULT NULL, ADD auto_response_generated_at DATETIME DEFAULT NULL, ADD auto_response_sent_at DATETIME DEFAULT NULL, CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE category category VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE feedback ADD CONSTRAINT FK_D2294458642B8210 FOREIGN KEY (admin_id) REFERENCES users (id)');
        $this->addSql('DROP INDEX admin_id ON feedback');
        $this->addSql('CREATE INDEX IDX_D2294458642B8210 ON feedback (admin_id)');
        $this->addSql('ALTER TABLE feedback ADD CONSTRAINT feedback_ibfk_2 FOREIGN KEY (admin_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE feedback_comments CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE date_creation date_creation DATETIME DEFAULT NULL, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY formation_ibfk_1');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY formation_ibfk_1');
        $this->addSql('ALTER TABLE formation CHANGE sujet sujet VARCHAR(255) DEFAULT NULL, CHANGE formateur formateur VARCHAR(255) DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL, CHANGE localisation localisation VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF642B8210 FOREIGN KEY (admin_id) REFERENCES users (id)');
        $this->addSql('DROP INDEX admin_id ON formation');
        $this->addSql('CREATE INDEX IDX_404021BF642B8210 ON formation (admin_id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT formation_ibfk_1 FOREIGN KEY (admin_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE offre_emploi DROP FOREIGN KEY offre_emploi_ibfk_1');
        $this->addSql('ALTER TABLE offre_emploi DROP FOREIGN KEY offre_emploi_ibfk_1');
        $this->addSql('ALTER TABLE offre_emploi CHANGE titre titre VARCHAR(255) DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE departement departement VARCHAR(255) DEFAULT NULL, CHANGE type_contrat type_contrat VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE offre_emploi ADD CONSTRAINT FK_132AD0D1642B8210 FOREIGN KEY (admin_id) REFERENCES users (id)');
        $this->addSql('DROP INDEX admin_id ON offre_emploi');
        $this->addSql('CREATE INDEX IDX_132AD0D1642B8210 ON offre_emploi (admin_id)');
        $this->addSql('ALTER TABLE offre_emploi ADD CONSTRAINT offre_emploi_ibfk_1 FOREIGN KEY (admin_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY participation_ibfk_2');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY participation_ibfk_1');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY participation_ibfk_2');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY participation_ibfk_1');
        $this->addSql('ALTER TABLE participation ADD statut VARCHAR(20) DEFAULT NULL, CHANGE resultat resultat VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F1B65292 FOREIGN KEY (employe_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F5200282E FOREIGN KEY (formation_id) REFERENCES formation (id)');
        $this->addSql('DROP INDEX employe_id ON participation');
        $this->addSql('CREATE INDEX IDX_AB55E24F1B65292 ON participation (employe_id)');
        $this->addSql('DROP INDEX formation_id ON participation');
        $this->addSql('CREATE INDEX IDX_AB55E24F5200282E ON participation (formation_id)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT participation_ibfk_2 FOREIGN KEY (employe_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT participation_ibfk_1 FOREIGN KEY (formation_id) REFERENCES formation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE publication DROP FOREIGN KEY publication_ibfk_1');
        $this->addSql('ALTER TABLE publication DROP FOREIGN KEY publication_ibfk_1');
        $this->addSql('ALTER TABLE publication CHANGE contenu contenu LONGTEXT NOT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT FK_AF3C6779A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('DROP INDEX user_id ON publication');
        $this->addSql('CREATE INDEX IDX_AF3C6779A76ED395 ON publication (user_id)');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT publication_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE publication_media DROP FOREIGN KEY publication_media_ibfk_1');
        $this->addSql('ALTER TABLE publication_media DROP FOREIGN KEY publication_media_ibfk_1');
        $this->addSql('ALTER TABLE publication_media CHANGE publication_id publication_id INT DEFAULT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE path path LONGTEXT NOT NULL');
        $this->addSql('ALTER TABLE publication_media ADD CONSTRAINT FK_8FF2E78038B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id)');
        $this->addSql('DROP INDEX publication_id ON publication_media');
        $this->addSql('CREATE INDEX IDX_8FF2E78038B217A7 ON publication_media (publication_id)');
        $this->addSql('ALTER TABLE publication_media ADD CONSTRAINT publication_media_ibfk_1 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY question_ibfk_1');
        $this->addSql('ALTER TABLE question CHANGE quiz_id quiz_id INT DEFAULT NULL, CHANGE question_text question_text LONGTEXT DEFAULT NULL, CHANGE type type VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX quiz_id ON question');
        $this->addSql('CREATE INDEX IDX_B6F7494E853CD175 ON question (quiz_id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT question_ibfk_1 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY quiz_ibfk_1');
        $this->addSql('ALTER TABLE quiz CHANGE offre_id offre_id INT DEFAULT NULL');
        $this->addSql('DROP INDEX offre_id ON quiz');
        $this->addSql('CREATE INDEX IDX_A412FA924CC8505A ON quiz (offre_id)');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT quiz_ibfk_1 FOREIGN KEY (offre_id) REFERENCES offre_emploi (id)');
        $this->addSql('ALTER TABLE reaction_publication DROP FOREIGN KEY reaction_publication_ibfk_1');
        $this->addSql('DROP INDEX unique_reaction ON reaction_publication');
        $this->addSql('ALTER TABLE reaction_publication CHANGE type type VARCHAR(20) NOT NULL');
        $this->addSql('ALTER TABLE reaction_publication ADD CONSTRAINT FK_EC2A804F38B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id)');
        $this->addSql('ALTER TABLE reaction_publication ADD CONSTRAINT FK_EC2A804FA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_EC2A804FA76ED395 ON reaction_publication (user_id)');
        $this->addSql('ALTER TABLE reponse_qcm DROP FOREIGN KEY reponse_qcm_ibfk_1');
        $this->addSql('ALTER TABLE reponse_qcm CHANGE question_id question_id INT DEFAULT NULL');
        $this->addSql('DROP INDEX question_id ON reponse_qcm');
        $this->addSql('CREATE INDEX IDX_BF0C6CD01E27F6BF ON reponse_qcm (question_id)');
        $this->addSql('ALTER TABLE reponse_qcm ADD CONSTRAINT reponse_qcm_ibfk_1 FOREIGN KEY (question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE reputation DROP FOREIGN KEY reputation_ibfk_1');
        $this->addSql('ALTER TABLE reputation CHANGE user_id user_id INT DEFAULT NULL, CHANGE total_score total_score INT DEFAULT NULL, CHANGE badge badge VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX user_id ON reputation');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CA177A5DA76ED395 ON reputation (user_id)');
        $this->addSql('ALTER TABLE reputation ADD CONSTRAINT reputation_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE resultat_quiz DROP FOREIGN KEY resultat_quiz_ibfk_2');
        $this->addSql('ALTER TABLE resultat_quiz DROP FOREIGN KEY resultat_quiz_ibfk_1');
        $this->addSql('ALTER TABLE resultat_quiz CHANGE candidat_id candidat_id INT DEFAULT NULL, CHANGE quiz_id quiz_id INT DEFAULT NULL, CHANGE score_pourcentage score_pourcentage NUMERIC(5, 2) DEFAULT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP INDEX candidat_id ON resultat_quiz');
        $this->addSql('CREATE INDEX IDX_2A776B38D0EB82 ON resultat_quiz (candidat_id)');
        $this->addSql('DROP INDEX quiz_id ON resultat_quiz');
        $this->addSql('CREATE INDEX IDX_2A776B3853CD175 ON resultat_quiz (quiz_id)');
        $this->addSql('ALTER TABLE resultat_quiz ADD CONSTRAINT resultat_quiz_ibfk_2 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE resultat_quiz ADD CONSTRAINT resultat_quiz_ibfk_1 FOREIGN KEY (candidat_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY fk_user_manager');
        $this->addSql('DROP INDEX email ON users');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY fk_user_manager');
        $this->addSql('ALTER TABLE users ADD is_active TINYINT(1) DEFAULT 1 NOT NULL, ADD cv_filename VARCHAR(255) DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD reputation_score INT DEFAULT 0 NOT NULL, CHANGE nom nom VARCHAR(255) NOT NULL, CHANGE prenom prenom VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE role role VARCHAR(20) DEFAULT NULL, CHANGE face_image face_image VARCHAR(255) DEFAULT NULL, CHANGE reset_token reset_token VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9783E3463 FOREIGN KEY (manager_id) REFERENCES users (id)');
        $this->addSql('DROP INDEX fk_user_manager ON users');
        $this->addSql('CREATE INDEX IDX_1483A5E9783E3463 ON users (manager_id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT fk_user_manager FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE action_logs DROP FOREIGN KEY FK_866E7D52A76ED395');
        $this->addSql('ALTER TABLE approval_history DROP FOREIGN KEY FK_B3FACF0DCAAC9A59');
        $this->addSql('ALTER TABLE approval_history DROP FOREIGN KEY FK_B3FACF0D2DFF238F');
        $this->addSql('ALTER TABLE approval_history DROP FOREIGN KEY FK_B3FACF0DBB23766C');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE planning_rules DROP FOREIGN KEY FK_183623A3783E3463');
        $this->addSql('DROP TABLE action_logs');
        $this->addSql('DROP TABLE approval_history');
        $this->addSql('DROP TABLE jours_feries');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE planning_rules');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C91B65292');
        $this->addSql('ALTER TABLE absence CHANGE type_absence type_absence ENUM(\'CONGE\', \'MALADIE\', \'RETARD\', \'AUTRE\') NOT NULL, CHANGE statut statut VARCHAR(50) DEFAULT NULL, CHANGE employe_id employe_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_765ae0c91b65292 ON absence');
        $this->addSql('CREATE INDEX employe_id ON absence (employe_id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C91B65292 FOREIGN KEY (employe_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY FK_E33BD3B88D0EB82');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY FK_E33BD3B84CC8505A');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY FK_E33BD3B88D0EB82');
        $this->addSql('ALTER TABLE candidature DROP FOREIGN KEY FK_E33BD3B84CC8505A');
        $this->addSql('ALTER TABLE candidature CHANGE statut statut VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT candidature_ibfk_2 FOREIGN KEY (offre_id) REFERENCES offre_emploi (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT candidature_ibfk_3 FOREIGN KEY (candidat_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_e33bd3b88d0eb82 ON candidature');
        $this->addSql('CREATE INDEX candidat_id ON candidature (candidat_id)');
        $this->addSql('DROP INDEX idx_e33bd3b84cc8505a ON candidature');
        $this->addSql('CREATE INDEX offre_id ON candidature (offre_id)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT FK_E33BD3B88D0EB82 FOREIGN KEY (candidat_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE candidature ADD CONSTRAINT FK_E33BD3B84CC8505A FOREIGN KEY (offre_id) REFERENCES offre_emploi (id)');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BC38B217A7');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BCA76ED395');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BC38B217A7');
        $this->addSql('ALTER TABLE commentaire DROP FOREIGN KEY FK_67F068BCA76ED395');
        $this->addSql('ALTER TABLE commentaire CHANGE contenu contenu TEXT NOT NULL');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT commentaire_ibfk_1 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT commentaire_ibfk_2 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_67f068bca76ed395 ON commentaire');
        $this->addSql('CREATE INDEX user_id ON commentaire (user_id)');
        $this->addSql('DROP INDEX idx_67f068bc38b217a7 ON commentaire');
        $this->addSql('CREATE INDEX publication_id ON commentaire (publication_id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC38B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY FK_2ED893482DFF238F');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY FK_2ED893482DFF238F');
        $this->addSql('ALTER TABLE conge DROP FOREIGN KEY FK_2ED89348783E3463');
        $this->addSql('ALTER TABLE conge CHANGE commentaire_validation commentaire_validation TEXT DEFAULT NULL, CHANGE absence_id absence_id INT NOT NULL');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT conge_ibfk_1 FOREIGN KEY (absence_id) REFERENCES absence (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_2ed89348783e3463 ON conge');
        $this->addSql('CREATE INDEX manager_id ON conge (manager_id)');
        $this->addSql('DROP INDEX uniq_2ed893482dff238f ON conge');
        $this->addSql('CREATE UNIQUE INDEX absence_id ON conge (absence_id)');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT FK_2ED893482DFF238F FOREIGN KEY (absence_id) REFERENCES absence (id)');
        $this->addSql('ALTER TABLE conge ADD CONSTRAINT FK_2ED89348783E3463 FOREIGN KEY (manager_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE entretien DROP FOREIGN KEY FK_2B58D6DAB6121583');
        $this->addSql('ALTER TABLE entretien DROP FOREIGN KEY FK_2B58D6DA642B8210');
        $this->addSql('ALTER TABLE entretien DROP FOREIGN KEY FK_2B58D6DA783E3463');
        $this->addSql('ALTER TABLE entretien CHANGE duree_minutes duree_minutes INT DEFAULT 60, CHANGE statut statut ENUM(\'PLANIFIE\', \'TERMINE\', \'ANNULE\', \'REPORTE\') DEFAULT \'PLANIFIE\', CHANGE commentaire commentaire TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE candidature_id candidature_id INT NOT NULL, CHANGE admin_id admin_id INT NOT NULL, CHANGE manager_id manager_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_2b58d6da642b8210 ON entretien');
        $this->addSql('CREATE INDEX admin_id ON entretien (admin_id)');
        $this->addSql('DROP INDEX idx_2b58d6da783e3463 ON entretien');
        $this->addSql('CREATE INDEX manager_id ON entretien (manager_id)');
        $this->addSql('DROP INDEX idx_2b58d6dab6121583 ON entretien');
        $this->addSql('CREATE INDEX candidature_id ON entretien (candidature_id)');
        $this->addSql('ALTER TABLE entretien ADD CONSTRAINT FK_2B58D6DAB6121583 FOREIGN KEY (candidature_id) REFERENCES candidature (id)');
        $this->addSql('ALTER TABLE entretien ADD CONSTRAINT FK_2B58D6DA642B8210 FOREIGN KEY (admin_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE entretien ADD CONSTRAINT FK_2B58D6DA783E3463 FOREIGN KEY (manager_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE feedback DROP FOREIGN KEY FK_D2294458642B8210');
        $this->addSql('ALTER TABLE feedback DROP FOREIGN KEY FK_D2294458642B8210');
        $this->addSql('ALTER TABLE feedback DROP priority, DROP auto_response, DROP auto_response_generated_at, DROP auto_response_sent_at, CHANGE contenu contenu TEXT NOT NULL, CHANGE category category VARCHAR(50) DEFAULT \'Autre\', CHANGE status status VARCHAR(50) DEFAULT \'nouveau\'');
        $this->addSql('ALTER TABLE feedback ADD CONSTRAINT feedback_ibfk_2 FOREIGN KEY (admin_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE INDEX employe_id ON feedback (employe_id)');
        $this->addSql('DROP INDEX idx_d2294458642b8210 ON feedback');
        $this->addSql('CREATE INDEX admin_id ON feedback (admin_id)');
        $this->addSql('ALTER TABLE feedback ADD CONSTRAINT FK_D2294458642B8210 FOREIGN KEY (admin_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE feedback_comments MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `primary` ON feedback_comments');
        $this->addSql('ALTER TABLE feedback_comments CHANGE id id INT NOT NULL, CHANGE contenu contenu TEXT NOT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BF642B8210');
        $this->addSql('ALTER TABLE formation DROP FOREIGN KEY FK_404021BF642B8210');
        $this->addSql('ALTER TABLE formation CHANGE sujet sujet VARCHAR(150) DEFAULT NULL, CHANGE formateur formateur VARCHAR(100) DEFAULT NULL, CHANGE type type VARCHAR(50) DEFAULT NULL, CHANGE localisation localisation VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT formation_ibfk_1 FOREIGN KEY (admin_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_404021bf642b8210 ON formation');
        $this->addSql('CREATE INDEX admin_id ON formation (admin_id)');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF642B8210 FOREIGN KEY (admin_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE offre_emploi DROP FOREIGN KEY FK_132AD0D1642B8210');
        $this->addSql('ALTER TABLE offre_emploi DROP FOREIGN KEY FK_132AD0D1642B8210');
        $this->addSql('ALTER TABLE offre_emploi CHANGE titre titre VARCHAR(100) DEFAULT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE departement departement VARCHAR(100) DEFAULT NULL, CHANGE type_contrat type_contrat VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE offre_emploi ADD CONSTRAINT offre_emploi_ibfk_1 FOREIGN KEY (admin_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('DROP INDEX idx_132ad0d1642b8210 ON offre_emploi');
        $this->addSql('CREATE INDEX admin_id ON offre_emploi (admin_id)');
        $this->addSql('ALTER TABLE offre_emploi ADD CONSTRAINT FK_132AD0D1642B8210 FOREIGN KEY (admin_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24F1B65292');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24F5200282E');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24F1B65292');
        $this->addSql('ALTER TABLE participation DROP FOREIGN KEY FK_AB55E24F5200282E');
        $this->addSql('ALTER TABLE participation DROP statut, CHANGE resultat resultat VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT participation_ibfk_2 FOREIGN KEY (employe_id) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT participation_ibfk_1 FOREIGN KEY (formation_id) REFERENCES formation (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_ab55e24f5200282e ON participation');
        $this->addSql('CREATE INDEX formation_id ON participation (formation_id)');
        $this->addSql('DROP INDEX idx_ab55e24f1b65292 ON participation');
        $this->addSql('CREATE INDEX employe_id ON participation (employe_id)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F1B65292 FOREIGN KEY (employe_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE participation ADD CONSTRAINT FK_AB55E24F5200282E FOREIGN KEY (formation_id) REFERENCES formation (id)');
        $this->addSql('ALTER TABLE publication DROP FOREIGN KEY FK_AF3C6779A76ED395');
        $this->addSql('ALTER TABLE publication DROP FOREIGN KEY FK_AF3C6779A76ED395');
        $this->addSql('ALTER TABLE publication CHANGE contenu contenu TEXT NOT NULL, CHANGE type type VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT publication_ibfk_1 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_af3c6779a76ed395 ON publication');
        $this->addSql('CREATE INDEX user_id ON publication (user_id)');
        $this->addSql('ALTER TABLE publication ADD CONSTRAINT FK_AF3C6779A76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE publication_media DROP FOREIGN KEY FK_8FF2E78038B217A7');
        $this->addSql('ALTER TABLE publication_media DROP FOREIGN KEY FK_8FF2E78038B217A7');
        $this->addSql('ALTER TABLE publication_media CHANGE type type VARCHAR(10) NOT NULL, CHANGE path path TEXT NOT NULL, CHANGE publication_id publication_id INT NOT NULL');
        $this->addSql('ALTER TABLE publication_media ADD CONSTRAINT publication_media_ibfk_1 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_8ff2e78038b217a7 ON publication_media');
        $this->addSql('CREATE INDEX publication_id ON publication_media (publication_id)');
        $this->addSql('ALTER TABLE publication_media ADD CONSTRAINT FK_8FF2E78038B217A7 FOREIGN KEY (publication_id) REFERENCES publication (id)');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY FK_B6F7494E853CD175');
        $this->addSql('ALTER TABLE question CHANGE question_text question_text TEXT DEFAULT NULL, CHANGE type type ENUM(\'QCM\', \'OUVERTE\') DEFAULT NULL, CHANGE quiz_id quiz_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_b6f7494e853cd175 ON question');
        $this->addSql('CREATE INDEX quiz_id ON question (quiz_id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE quiz DROP FOREIGN KEY FK_A412FA924CC8505A');
        $this->addSql('ALTER TABLE quiz CHANGE offre_id offre_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_a412fa924cc8505a ON quiz');
        $this->addSql('CREATE INDEX offre_id ON quiz (offre_id)');
        $this->addSql('ALTER TABLE quiz ADD CONSTRAINT FK_A412FA924CC8505A FOREIGN KEY (offre_id) REFERENCES offre_emploi (id)');
        $this->addSql('ALTER TABLE reaction_publication DROP FOREIGN KEY FK_EC2A804F38B217A7');
        $this->addSql('ALTER TABLE reaction_publication DROP FOREIGN KEY FK_EC2A804FA76ED395');
        $this->addSql('DROP INDEX IDX_EC2A804FA76ED395 ON reaction_publication');
        $this->addSql('ALTER TABLE reaction_publication CHANGE type type ENUM(\'LIKE\', \'DISLIKE\') NOT NULL');
        $this->addSql('ALTER TABLE reaction_publication ADD CONSTRAINT reaction_publication_ibfk_1 FOREIGN KEY (publication_id) REFERENCES publication (id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX unique_reaction ON reaction_publication (publication_id, user_id)');
        $this->addSql('ALTER TABLE reponse_qcm DROP FOREIGN KEY FK_BF0C6CD01E27F6BF');
        $this->addSql('ALTER TABLE reponse_qcm CHANGE question_id question_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_bf0c6cd01e27f6bf ON reponse_qcm');
        $this->addSql('CREATE INDEX question_id ON reponse_qcm (question_id)');
        $this->addSql('ALTER TABLE reponse_qcm ADD CONSTRAINT FK_BF0C6CD01E27F6BF FOREIGN KEY (question_id) REFERENCES question (id)');
        $this->addSql('ALTER TABLE reputation DROP FOREIGN KEY FK_CA177A5DA76ED395');
        $this->addSql('ALTER TABLE reputation CHANGE total_score total_score INT DEFAULT 0, CHANGE badge badge VARCHAR(20) DEFAULT \'DEBUTANT\', CHANGE user_id user_id INT NOT NULL');
        $this->addSql('DROP INDEX uniq_ca177a5da76ed395 ON reputation');
        $this->addSql('CREATE UNIQUE INDEX user_id ON reputation (user_id)');
        $this->addSql('ALTER TABLE reputation ADD CONSTRAINT FK_CA177A5DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE resultat_quiz DROP FOREIGN KEY FK_2A776B38D0EB82');
        $this->addSql('ALTER TABLE resultat_quiz DROP FOREIGN KEY FK_2A776B3853CD175');
        $this->addSql('ALTER TABLE resultat_quiz CHANGE score_pourcentage score_pourcentage DOUBLE PRECISION DEFAULT NULL, CHANGE statut statut ENUM(\'REUSSI\', \'ECHEC\') DEFAULT NULL, CHANGE candidat_id candidat_id INT NOT NULL, CHANGE quiz_id quiz_id INT NOT NULL');
        $this->addSql('DROP INDEX idx_2a776b3853cd175 ON resultat_quiz');
        $this->addSql('CREATE INDEX quiz_id ON resultat_quiz (quiz_id)');
        $this->addSql('DROP INDEX idx_2a776b38d0eb82 ON resultat_quiz');
        $this->addSql('CREATE INDEX candidat_id ON resultat_quiz (candidat_id)');
        $this->addSql('ALTER TABLE resultat_quiz ADD CONSTRAINT FK_2A776B38D0EB82 FOREIGN KEY (candidat_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE resultat_quiz ADD CONSTRAINT FK_2A776B3853CD175 FOREIGN KEY (quiz_id) REFERENCES quiz (id)');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9783E3463');
        $this->addSql('ALTER TABLE users DROP FOREIGN KEY FK_1483A5E9783E3463');
        $this->addSql('ALTER TABLE users DROP is_active, DROP cv_filename, DROP updated_at, DROP reputation_score, CHANGE nom nom VARCHAR(100) NOT NULL, CHANGE prenom prenom VARCHAR(100) NOT NULL, CHANGE email email VARCHAR(150) NOT NULL, CHANGE role role ENUM(\'ADMIN_RH\', \'MANAGER\', \'EMPLOYE\', \'CANDIDAT\') NOT NULL, CHANGE face_image face_image BLOB DEFAULT NULL, CHANGE reset_token reset_token VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT fk_user_manager FOREIGN KEY (manager_id) REFERENCES users (id) ON DELETE SET NULL');
        $this->addSql('CREATE UNIQUE INDEX email ON users (email)');
        $this->addSql('DROP INDEX idx_1483a5e9783e3463 ON users');
        $this->addSql('CREATE INDEX fk_user_manager ON users (manager_id)');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9783E3463 FOREIGN KEY (manager_id) REFERENCES users (id)');
    }
}
